fail fast in all scripts

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,8 +1,12 @@
 #!/bin/bash
 
+# fail fast on errors
+set -e
+
 BUILD_DIR=$1
 CACHE_DIR=$2
 export ENV_DIR=$3
+
 TMP_DIR=$(mktemp -d)
 APP_DIR=$TMP_DIR/app
 KEY_PROVIDER=$(cat ${ENV_DIR}/KEY_PROVIDER)
